import type { QuestionSeed } from "./types";

// 16 easy (difficulty 1), 16 medium (difficulty 2), 8 hard (difficulty 3)
export const biologiaQuestions: QuestionSeed[] = [
  // ── Easy ──────────────────────────────────────────────────────────────────
  {
    body: "Qual organela celular é responsável pela produção de energia (ATP) nas células eucarióticas?",
    options: ["Ribossomo", "Mitocôndria", "Núcleo", "Retículo endoplasmático"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "O DNA é composto de unidades básicas chamadas:",
    options: ["Nucleotídeos", "Aminoácidos", "Lipídios", "Polissacarídeos"],
    correctOptionIndex: 0,
    difficulty: 1,
  },
  {
    body: "O processo pelo qual as plantas produzem seu próprio alimento usando luz solar é chamado de:",
    options: ["Respiração celular", "Fermentação", "Fotossíntese", "Digestão"],
    correctOptionIndex: 2,
    difficulty: 1,
    source: "ENEM 2017",
  },
  {
    body: "Qual é a unidade básica de todos os seres vivos?",
    options: ["Órgão", "Tecido", "Sistema", "Célula"],
    correctOptionIndex: 3,
    difficulty: 1,
  },
  {
    body: "Qual tipo sanguíneo não possui antígenos na superfície das hemácias?",
    options: ["Tipo A", "Tipo O", "Tipo B", "Tipo AB"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Quantos cromossomos tem a célula somática humana?",
    options: ["23", "46", "48", "44"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "As bactérias são organismos:",
    options: [
      "Eucarióticos sem núcleo",
      "Procarióticos sem núcleo definido",
      "Eucarióticos com núcleo",
      "Multicelulares",
    ],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Qual processo celular produz as células sexuais (gametas) nos organismos eucarióticos?",
    options: ["Mitose", "Meiose", "Cariocinese", "Citocinese"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Qual é a fórmula molecular da água?",
    options: ["H₂O₂", "HO", "H₂O", "H₃O"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Onde está armazenada a informação genética na célula eucariótica?",
    options: ["Citoplasma", "Membrana plasmática", "Núcleo", "Ribossomo"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "As plantas liberam oxigênio como subproduto de qual processo?",
    options: ["Respiração aeróbia", "Fotossíntese", "Fermentação", "Excreção"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Um ecossistema é formado por:",
    options: [
      "Apenas animais e plantas",
      "Comunidade biótica e fatores abióticos",
      "Apenas seres vivos",
      "Apenas fatores físicos e químicos",
    ],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Um alelo dominante:",
    options: [
      "Nunca se expressa",
      "Mascara o efeito do alelo recessivo",
      "Só se expressa em homozigose",
      "É sempre deletério",
    ],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Os vertebrados possuem:",
    options: [
      "Exoesqueleto de quitina",
      "Coluna vertebral",
      "Três pares de patas",
      "Corpo segmentado em três partes",
    ],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Os insetos possuem quantas patas?",
    options: ["4", "8", "6", "10"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Qual órgão é responsável por bombear o sangue no corpo humano?",
    options: ["Pulmão", "Fígado", "Rim", "Coração"],
    correctOptionIndex: 3,
    difficulty: 1,
  },
  // ── Medium ────────────────────────────────────────────────────────────────
  {
    body: "Qual enzima presente na saliva inicia a digestão do amido?",
    options: ["Pepsina", "Amilase", "Lipase", "Tripsina"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A mitose produz células-filhas com:",
    options: [
      "Metade do número de cromossomos da célula-mãe",
      "O mesmo número de cromossomos da célula-mãe",
      "O dobro de cromossomos",
      "Número variável de cromossomos",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "No DNA, qual base nitrogenada se pareia com a adenina?",
    options: ["Guanina", "Citosina", "Timina", "Uracila"],
    correctOptionIndex: 2,
    difficulty: 2,
    source: "ENEM 2020",
  },
  {
    body: "A vacinação protege o organismo estimulando:",
    options: [
      "A produção de anticorpos pelo sistema imunológico",
      "A destruição do patógeno por calor",
      "O sistema digestório a eliminar toxinas",
      "A febre para matar microrganismos",
    ],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "A fotossíntese ocorre em qual organela celular?",
    options: ["Cloroplasto", "Mitocôndria", "Vacúolo", "Ribossomo"],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "Qual sistema regula a glicemia (nível de açúcar no sangue)?",
    options: ["Sistema nervoso", "Sistema digestório", "Sistema endócrino", "Sistema excretor"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "O crossing-over (permutação) ocorre durante qual fase da meiose?",
    options: [
      "Meiose I — Prófase I",
      "Meiose II — Metáfase II",
      "Meiose I — Anáfase I",
      "Meiose II — Prófase II",
    ],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "A transpiração nas plantas é a perda de água principalmente por meio de estruturas chamadas:",
    options: ["Raízes", "Estômatos", "Lenticelas", "Flores"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "As bactérias se reproduzem principalmente por:",
    options: ["Meiose", "Divisão binária (fissão binária)", "Gemulação", "Esporulação sexuada"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Qual câmara cardíaca bombeia sangue para os pulmões?",
    options: ["Átrio esquerdo", "Ventrículo esquerdo", "Átrio direito", "Ventrículo direito"],
    correctOptionIndex: 3,
    difficulty: 2,
  },
  {
    body: "Os alelos que determinam o mesmo caráter se localizam em:",
    options: [
      "Cromossomos homólogos",
      "Cromossomos sexuais apenas",
      "O mesmo cromossomo",
      "Locais aleatórios do genoma",
    ],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "O ATP armazena energia em forma de:",
    options: ["Energia elétrica", "Energia mecânica", "Energia química", "Energia luminosa"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "Um herbívoro se alimenta de:",
    options: ["Animais", "Plantas e outros vegetais", "Fungos apenas", "Animais e plantas"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "O primeiro nível trófico de uma cadeia alimentar é ocupado pelos:",
    options: [
      "Decompositores",
      "Produtores (plantas)",
      "Consumidores primários",
      "Consumidores secundários",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "O carbono entra na componente biótica do ciclo biogeoquímico principalmente via:",
    options: ["Decomposição", "Fotossíntese", "Respiração", "Combustão"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Os antibióticos são eficazes no combate a:",
    options: ["Vírus", "Fungos", "Bactérias", "Protozoários apenas"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  // ── Hard ──────────────────────────────────────────────────────────────────
  {
    body: "A técnica PCR (Reação em Cadeia da Polimerase) é usada para:",
    options: [
      "Amplificar segmentos específicos de DNA",
      "Sequenciar proteínas",
      "Editar genes de forma permanente",
      "Produzir anticorpos monoclonais",
    ],
    correctOptionIndex: 0,
    difficulty: 3,
  },
  {
    body: "A tecnologia CRISPR-Cas9 é classificada como uma ferramenta de:",
    options: ["Microscopia eletrônica", "Edição gênica", "Eletroforese", "Cromatografia"],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "O RNA mensageiro (mRNA) é traduzido em proteínas nos:",
    options: ["Núcleos", "Mitocôndrias", "Ribossomos", "Vacúolos"],
    correctOptionIndex: 2,
    difficulty: 3,
  },
  {
    body: "O equilíbrio de Hardy-Weinberg pressupõe, entre outras condições, que a população seja:",
    options: [
      "Grande e com acasalamento aleatório",
      "Pequena e isolada",
      "Sujeita à seleção natural intensa",
      "Com alta taxa de mutação",
    ],
    correctOptionIndex: 0,
    difficulty: 3,
    source: "ENEM 2021",
  },
  {
    body: "As enzimas de restrição (endonucleases) cortam o DNA em:",
    options: [
      "Posições aleatórias",
      "Sequências específicas de nucleotídeos",
      "Apenas nas extremidades",
      "Regiões de RNA",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "A replicação semiconservativa do DNA significa que:",
    options: [
      "Cada nova fita é completamente nova",
      "Cada molécula-filha contém uma fita parental e uma nova",
      "Ambas as fitas são conservadas sem mudança",
      "Apenas metade do DNA é replicada",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "Epigenética refere-se a mudanças na:",
    options: [
      "Sequência de nucleotídeos do DNA",
      "Expressão gênica sem alterar a sequência do DNA",
      "Estrutura do ribossomo",
      "Síntese de ATP",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "Na síntese proteica, a etapa chamada 'tradução' converte:",
    options: ["DNA em RNA", "mRNA em proteína", "Proteína em aminoácidos", "tRNA em mRNA"],
    correctOptionIndex: 1,
    difficulty: 3,
  },
];
