import type { QuestionSeed } from "./types";

// 16 easy (difficulty 1), 16 medium (difficulty 2), 8 hard (difficulty 3)
export const fisicaQuestions: QuestionSeed[] = [
  // ── Easy ──────────────────────────────────────────────────────────────────
  {
    body: "Um móvel percorre 100 m em 10 s com velocidade constante. Qual é sua velocidade?",
    options: ["10 m/s", "100 m/s", "1000 m/s", "1 m/s"],
    correctOptionIndex: 0,
    difficulty: 1,
  },
  {
    body: "Pela Segunda Lei de Newton, F = ma. Qual é a força sobre um objeto de 2 kg com aceleração de 5 m/s²?",
    options: ["2,5 N", "7 N", "10 N", "3 N"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Qual é a unidade de resistência elétrica no SI?",
    options: ["Ampere", "Ohm", "Watt", "Farad"],
    correctOptionIndex: 1,
    difficulty: 1,
    source: "ENEM 2016",
  },
  {
    body: "Qual tipo de onda não precisa de um meio material para se propagar?",
    options: ["Sonora", "Sísmica", "Eletromagnética", "Aquática"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "A aceleração da gravidade próxima à superfície da Terra é aproximadamente:",
    options: ["5 m/s²", "15 m/s²", "20 m/s²", "10 m/s²"],
    correctOptionIndex: 3,
    difficulty: 1,
  },
  {
    body: "Trabalho = Força × deslocamento. Qual o trabalho realizado por uma força de 5 N ao deslocar um objeto 3 m?",
    options: ["8 J", "15 J", "2 J", "1,67 J"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "O voltímetro é usado para medir:",
    options: [
      "Corrente elétrica",
      "Resistência",
      "Tensão elétrica (diferença de potencial)",
      "Potência",
    ],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "A velocidade da luz no vácuo é aproximadamente:",
    options: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "A cor com maior frequência no espectro visível é:",
    options: ["Vermelho", "Violeta", "Verde", "Amarelo"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Potência = Trabalho / tempo. Se W = 60 J e t = 3 s, qual é a potência?",
    options: ["180 W", "20 W", "57 W", "63 W"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Qual é a unidade de força no Sistema Internacional (SI)?",
    options: ["Joule", "Pascal", "Newton", "Watt"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Em qual meio o som se propaga mais rapidamente?",
    options: ["Vácuo", "Gases", "Líquidos", "Sólidos"],
    correctOptionIndex: 3,
    difficulty: 1,
  },
  {
    body: "A energia cinética depende de quais grandezas?",
    options: ["Peso e altura", "Massa e velocidade", "Volume e pressão", "Carga e tensão"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "O zero absoluto corresponde a:",
    options: ["0 °C", "−100 °C", "−273 °C (≈ 0 K)", "−373 °C"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "O trabalho realizado por uma força perpendicular ao deslocamento é:",
    options: ["Máximo", "Nulo", "Negativo", "Indeterminado"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Qual grandeza é conservada em todas as colisões, elásticas e inelásticas?",
    options: [
      "Energia cinética",
      "Quantidade de movimento (momento linear)",
      "Energia mecânica",
      "Velocidade",
    ],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  // ── Medium ────────────────────────────────────────────────────────────────
  {
    body: "Pela Lei de Ohm, V = RI. Com V = 12 V e R = 4 Ω, qual é a corrente I?",
    options: ["3 A", "48 A", "0,33 A", "8 A"],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "A Lei de Snell-Descartes descreve o fenômeno da:",
    options: ["Reflexão da luz", "Refração da luz", "Difração da luz", "Polarização da luz"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "As linhas do campo magnético ao redor de um fio condutor reto são:",
    options: ["Radiais", "Paralelas ao fio", "Circulares concêntricas ao fio", "Helicoidais"],
    correctOptionIndex: 2,
    difficulty: 2,
    source: "ENEM 2019",
  },
  {
    body: "A Primeira Lei da Termodinâmica enuncia a conservação de qual grandeza?",
    options: ["Entropia", "Temperatura", "Energia", "Pressão"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "A ressonância ocorre quando a frequência de oscilação forçada é igual a:",
    options: [
      "O dobro da frequência natural",
      "A frequência natural do sistema",
      "Metade da frequência natural",
      "Zero",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A aceleração centrípeta de um objeto em movimento circular é dada por:",
    options: ["v/r", "v²/r", "v²·r", "r/v²"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "As ondas sonoras são ondas:",
    options: [
      "Transversais eletromagnéticas",
      "Longitudinais mecânicas",
      "Transversais mecânicas",
      "Eletromagnéticas longitudinais",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Qual é a unidade de capacitância elétrica no SI?",
    options: ["Ohm", "Farad", "Henry", "Siemens"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "O efeito Doppler é observado quando há movimento relativo entre fonte e observador de:",
    options: ["Luz apenas", "Ondas em geral", "Apenas ondas mecânicas", "Apenas corrente elétrica"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Pressão = Força / Área. Com F = 100 N e A = 2 m², qual é a pressão?",
    options: ["200 Pa", "50 Pa", "100 Pa", "0,02 Pa"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "O campo elétrico criado por uma carga positiva aponta em qual direção?",
    options: [
      "Para a carga",
      "Para fora da carga (afastando-se)",
      "Perpendicular à carga",
      "Não possui direção definida",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A velocidade angular é medida em:",
    options: ["m/s", "rad/s", "Hz/m", "m/s²"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A Lei de Coulomb descreve a força entre:",
    options: [
      "Massas gravitacionais",
      "Cargas elétricas",
      "Polos magnéticos",
      "Moléculas em gases",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Em um transformador ideal, a relação entre tensões é proporcional à relação entre:",
    options: ["Correntes", "Resistências", "Número de espiras", "Potências"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "A força de empuxo sobre um objeto submerso é igual ao peso do fluido:",
    options: [
      "Na superfície do objeto",
      "Deslocado pelo objeto",
      "Em torno do objeto",
      "Acima do objeto",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A decaimento radioativo é um processo de natureza:",
    options: ["Química", "Nuclear", "Elétrica", "Óptica"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  // ── Hard ──────────────────────────────────────────────────────────────────
  {
    body: "O Princípio da Incerteza de Heisenberg estabelece que Δx · Δp ≥:",
    options: ["h", "ℏ/2", "h/4π", "ℏ"],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "Segundo a Relatividade Especial, a massa relativística de um objeto aumenta com:",
    options: ["A temperatura", "A velocidade", "A pressão", "A altura"],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "A energia de um fóton é dada por E =:",
    options: ["mc²", "hf", "½mv²", "qV"],
    correctOptionIndex: 1,
    difficulty: 3,
    source: "ENEM 2022",
  },
  {
    body: "A Lei de Gauss relaciona o fluxo elétrico através de uma superfície fechada com:",
    options: [
      "A carga elétrica total no interior",
      "O campo magnético externo",
      "A corrente que flui pela superfície",
      "A tensão aplicada",
    ],
    correctOptionIndex: 0,
    difficulty: 3,
  },
  {
    body: "Nos supercondutores, a resistência elétrica é:",
    options: ["Muito alta", "Zero", "Igual à resistência normal", "Negativa"],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "O comprimento de onda de De Broglie de uma partícula é dado por λ =:",
    options: ["h/p", "p/h", "hv", "E/c"],
    correctOptionIndex: 0,
    difficulty: 3,
  },
  {
    body: "A radiação de corpo negro é descrita quantitativamente pela lei de:",
    options: ["Newton", "Faraday", "Planck", "Bohr"],
    correctOptionIndex: 2,
    difficulty: 3,
  },
  {
    body: "A fissão nuclear libera energia de acordo com a relação:",
    options: ["E = hf", "E = mc²", "E = qV", "E = ½mv²"],
    correctOptionIndex: 1,
    difficulty: 3,
  },
];
