import type { QuestionSeed } from "./types";

// 16 easy (difficulty 1), 16 medium (difficulty 2), 8 hard (difficulty 3)
export const matematicaQuestions: QuestionSeed[] = [
  // ── Easy ──────────────────────────────────────────────────────────────────
  {
    body: "Qual é 25% de 200?",
    options: ["50", "40", "60", "25"],
    correctOptionIndex: 0,
    difficulty: 1,
    source: "ENEM 2018",
  },
  {
    body: "Quanto é √144?",
    options: ["11", "12", "13", "14"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Qual é o valor de 2³?",
    options: ["6", "4", "8", "16"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Um retângulo tem lados de 6 m e 4 m. Qual é sua área?",
    options: ["24 m²", "20 m²", "10 m²", "12 m²"],
    correctOptionIndex: 0,
    difficulty: 1,
  },
  {
    body: "Resolva: 3x + 6 = 15. Qual é o valor de x?",
    options: ["2", "3", "4", "5"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Na progressão aritmética 2, 5, 8, 11, ... qual é a razão?",
    options: ["3", "2", "4", "5"],
    correctOptionIndex: 0,
    difficulty: 1,
  },
  {
    body: "Qual é o perímetro de um quadrado com lado de 5 cm?",
    options: ["15 cm", "25 cm", "20 cm", "10 cm"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Como se escreve 0,5 como fração irredutível?",
    options: ["1/2", "2/5", "5/10", "1/5"],
    correctOptionIndex: 0,
    difficulty: 1,
  },
  {
    body: "Quanto é 15% de 80?",
    options: ["10", "12", "15", "8"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Qual é o volume de um cubo com aresta de 3 cm?",
    options: ["27 cm³", "9 cm³", "18 cm³", "12 cm³"],
    correctOptionIndex: 0,
    difficulty: 1,
  },
  {
    body: "A soma dos ângulos internos de um triângulo é:",
    options: ["90°", "180°", "270°", "360°"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Qual é o mínimo múltiplo comum (MMC) de 4 e 6?",
    options: ["8", "10", "12", "24"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Quanto é (−3) × (−4)?",
    options: ["12", "−12", "7", "−7"],
    correctOptionIndex: 0,
    difficulty: 1,
  },
  {
    body: "Qual é a média aritmética de 2, 4, 6, 8 e 10?",
    options: ["5", "6", "7", "8"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Quanto é 2/3 + 1/6?",
    options: ["3/9", "3/6", "5/6", "4/6"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Um carro viaja a 60 km/h durante 2 horas. Que distância percorre?",
    options: ["120 km", "100 km", "90 km", "30 km"],
    correctOptionIndex: 0,
    difficulty: 1,
  },
  // ── Medium ────────────────────────────────────────────────────────────────
  {
    body: "Quais são as raízes da equação x² − 5x + 6 = 0?",
    options: ["x=1 e x=6", "x=2 e x=3", "x=−2 e x=−3", "x=1 e x=5"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Quanto vale log₂(8)?",
    options: ["3", "4", "2", "6"],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "Qual é o valor de sen(30°)?",
    options: ["√3/2", "√2/2", "1/2", "1"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "Qual é a área de um círculo de raio 5 cm?",
    options: ["25π cm²", "10π cm²", "5π cm²", "50π cm²"],
    correctOptionIndex: 0,
    difficulty: 2,
    source: "ENEM 2019",
  },
  {
    body: "Na progressão geométrica 3, 6, 12, ..., qual é o 6º termo?",
    options: ["48", "96", "72", "192"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Qual é a probabilidade de obter face 3 ao lançar um dado justo?",
    options: ["1/6", "1/3", "1/2", "2/6"],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "Dada f(x) = 2x + 1, qual é f(3)?",
    options: ["5", "6", "7", "8"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "Qual é a mediana do conjunto {1, 3, 5, 7, 9}?",
    options: ["3", "5", "7", "9"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Qual é a distância entre os pontos A(0,0) e B(3,4)?",
    options: ["5", "7", "3", "4"],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "Qual é o vértice da parábola f(x) = x² − 4x + 3?",
    options: ["(1, 0)", "(3, 0)", "(2, −1)", "(−2, 1)"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "Qual é o coeficiente angular da reta y = 3x − 2?",
    options: ["3", "−2", "2", "−3"],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "Quanto é 3! (fatorial de 3)?",
    options: ["3", "6", "9", "12"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Qual é o complemento de um ângulo de 70°?",
    options: ["110°", "30°", "20°", "90°"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "Quanto é tg(45°)?",
    options: ["1", "0", "√2", "√3"],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "Qual é a soma dos ângulos internos de um hexágono regular?",
    options: ["540°", "720°", "900°", "1080°"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Qual é aproximadamente o valor de e (número de Euler)?",
    options: ["2,718", "3,141", "1,618", "1,414"],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  // ── Hard ──────────────────────────────────────────────────────────────────
  {
    body: "Qual é a derivada de f(x) = x³?",
    options: ["x²", "3x²", "3x", "x³/3"],
    correctOptionIndex: 1,
    difficulty: 3,
    source: "ENEM 2022",
  },
  {
    body: "Qual é o valor de ∫₀¹ x dx?",
    options: ["1/2", "1", "2", "1/3"],
    correctOptionIndex: 0,
    difficulty: 3,
  },
  {
    body: "Qual é o valor de i² onde i é a unidade imaginária?",
    options: ["1", "i", "−1", "−i"],
    correctOptionIndex: 2,
    difficulty: 3,
  },
  {
    body: "Quantas combinações de 3 elementos podemos formar com 10 elementos distintos? C(10,3) = ?",
    options: ["120", "720", "30", "10"],
    correctOptionIndex: 0,
    difficulty: 3,
  },
  {
    body: "A soma de uma progressão geométrica infinita com a = 1 e r = 1/2 é:",
    options: ["1", "2", "3", "4"],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "Qual é o terceiro lado de um triângulo retângulo com catetos 7 e 24?",
    options: ["31", "20", "25", "23"],
    correctOptionIndex: 2,
    difficulty: 3,
  },
  {
    body: "Quanto é ln(e²)?",
    options: ["2", "e", "e²", "1"],
    correctOptionIndex: 0,
    difficulty: 3,
  },
  {
    body: "Quantos números primos existem menores que 20?",
    options: ["7", "8", "9", "6"],
    correctOptionIndex: 1,
    difficulty: 3,
  },
];
