import type { QuestionSeed } from "./types";

// 16 easy (difficulty 1), 16 medium (difficulty 2), 8 hard (difficulty 3)
export const portuguesQuestions: QuestionSeed[] = [
  // ── Easy ──────────────────────────────────────────────────────────────────
  {
    body: 'Na oração "O menino correu rapidamente", a palavra "correu" é classificada como:',
    options: ["Substantivo", "Verbo", "Adjetivo", "Advérbio"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: 'A palavra "escola" possui quantas sílabas?',
    options: ["1", "2", "3", "4"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: 'Qual é o antônimo de "feliz"?',
    options: ["Alegre", "Triste", "Animado", "Contente"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: 'Qual é o sujeito da oração "As crianças brincam no parque"?',
    options: ["No parque", "Brincam", "As crianças", "No"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Qual das seguintes palavras é um substantivo?",
    options: ["Bonito", "Casa", "Correr", "Rapidamente"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: 'Usa-se "há" (de haver) para indicar:',
    options: ["Distância espacial", "Tempo decorrido no passado", "Obrigação", "Futuro próximo"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: 'Qual é o plural de "lápis"?',
    options: ["lápises", "lápis", "lápisses", "lápins"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: 'Na oração "João comprou um livro", "um livro" exerce a função de:',
    options: ["Sujeito", "Predicado verbal", "Objeto direto", "Complemento nominal"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Usamos letra maiúscula para iniciar:",
    options: [
      "Qualquer substantivo",
      "Nomes próprios e início de frase",
      "Todos os adjetivos",
      "Palavras em destaque",
    ],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: 'A conjunção "mas" é classificada como:',
    options: ["Aditiva", "Adversativa", "Conclusiva", "Explicativa"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: 'Qual é o feminino de "o artista"?',
    options: ["o artista (invariável)", "a artiste", "a artista", "a artisto"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: 'Na frase "Ela chegou cedo", "cedo" é:',
    options: ["Adjetivo", "Substantivo", "Verbo", "Advérbio de tempo"],
    correctOptionIndex: 3,
    difficulty: 1,
  },
  {
    body: "O ponto-final é usado para indicar:",
    options: [
      "Enumeração",
      "Pausa longa no final de período declarativo",
      "Interrogação",
      "Exclamação",
    ],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: '"Não vim" é um exemplo de oração:',
    options: ["Afirmativa", "Negativa", "Interrogativa", "Exclamativa"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "O pronome relativo usado para se referir a coisas é principalmente:",
    options: ["Quem", "Cujo", "Que", "Onde"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "O verbo da oração deve concordar em número e pessoa com o:",
    options: ["Objeto direto", "Sujeito", "Predicado", "Complemento circunstancial"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  // ── Medium ────────────────────────────────────────────────────────────────
  {
    body: 'A expressão "O tempo é dinheiro" é um exemplo de:',
    options: ["Comparação (símile)", "Metáfora", "Metonímia", "Hipérbole"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A crônica é um gênero textual caracterizado por:",
    options: [
      "Narrar grandes façanhas heróicas em versos",
      "Relatar fatos do cotidiano com linguagem leve e reflexiva",
      "Analisar tecnicamente fenômenos científicos",
      "Apresentar argumentos formais sobre teses acadêmicas",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
    source: "ENEM 2018",
  },
  {
    body: "A intertextualidade em um texto consiste em:",
    options: [
      "Repetição de palavras para dar ênfase",
      "Referência a outros textos ou obras na construção do sentido",
      "Uso de linguagem técnica e especializada",
      "Emprego de muitos parágrafos curtos",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: 'A figura de linguagem presente em "silêncio ensurdecedor" é:',
    options: ["Metáfora", "Oxímoro (paradoxo)", "Aliteração", "Eufemismo"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A ironia, como recurso expressivo, consiste em:",
    options: [
      "Exagerar propositalmente a realidade",
      "Dizer o oposto do que se pretende afirmar",
      "Suavizar uma ideia desagradável",
      'Comparar dois elementos com o uso de "como"',
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A estrutura básica de um texto dissertativo-argumentativo inclui:",
    options: [
      "Apenas introdução e conclusão",
      "Tese, argumentos e conclusão",
      "Narração, descrição e conclusão",
      "Problema, hipótese e metodologia",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "O Modernismo brasileiro teve início com a Semana de Arte Moderna em:",
    options: ["1889", "1922", "1945", "1964"],
    correctOptionIndex: 1,
    difficulty: 2,
    source: "ENEM 2019",
  },
  {
    body: "Uma oração subordinada adjetiva modifica um:",
    options: [
      "Verbo da oração principal",
      "Substantivo ou pronome da oração principal",
      "Adjetivo da oração principal",
      "Advérbio da oração principal",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A voz passiva analítica é construída com o verbo auxiliar:",
    options: [
      "Ter + infinitivo",
      "Ser + particípio passado",
      "Estar + gerúndio",
      "Haver + infinitivo",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A poesia épica tem como principal característica:",
    options: [
      "A expressão de sentimentos subjetivos do eu lírico",
      "A narração de façanhas heroicas de interesse coletivo",
      "O registro de fatos cotidianos em linguagem coloquial",
      "A representação de diálogos entre personagens",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A poesia lírica tem como principal característica:",
    options: [
      "Narrar aventuras de heróis nacionais",
      "Expressar emoções e sentimentos pessoais do eu poético",
      "Descrever batalhas históricas",
      "Apresentar argumento filosófico em prosa",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: 'A conjunção "embora" introduz uma oração subordinada:',
    options: ["Causal", "Concessiva", "Condicional", "Consecutiva"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "No discurso direto, as falas das personagens são introduzidas por:",
    options: [
      "Travessão ou aspas e verbo dicendi",
      "Apenas vírgula",
      "Parênteses obrigatórios",
      "Dois pontos sem qualquer pontuação adicional",
    ],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "O narrador onisciente é aquele que:",
    options: [
      "Participa da história como personagem",
      "Conhece pensamentos e ações de todos os personagens",
      "Observa apenas o exterior das personagens",
      "Relata apenas o que testemunhou pessoalmente",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A coesão textual é obtida pelo uso de:",
    options: [
      "Palavras difíceis e rebuscadas",
      "Conectivos e recursos de referência que articulam as partes do texto",
      "Parágrafos longos sem pontuação",
      "Repetição do mesmo vocabulário",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A conotação é o uso das palavras em sentido:",
    options: [
      "Literal e dicionarizado",
      "Figurado, além do significado original",
      "Técnico e especializado",
      "Regional e dialetal",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  // ── Hard ──────────────────────────────────────────────────────────────────
  {
    body: "O estruturalismo linguístico, desenvolvido a partir de Saussure, ocupa-se da:",
    options: [
      "Estrutura interna da língua como sistema de relações",
      "História das mudanças fonéticas ao longo do tempo",
      "Análise discursiva da ideologia nos textos",
      "Psicologia da aquisição da linguagem",
    ],
    correctOptionIndex: 0,
    difficulty: 3,
    source: "ENEM 2022",
  },
  {
    body: "O conceito de dialogismo de Bakhtin estabelece que todo enunciado:",
    options: [
      "É autônomo e independente de outros discursos",
      "Responde a enunciados anteriores e antecipa respostas futuras",
      "Deve seguir as normas gramaticais da língua culta",
      "É determinado exclusivamente pelo contexto histórico",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "O Naturalismo distingue-se do Realismo por incorporar:",
    options: [
      "A idealização romântica dos personagens",
      "O determinismo biológico e social, tratando o homem como produto do ambiente e da hereditariedade",
      "A valorização do lirismo e da subjetividade",
      "A linguagem simbólica e hermética",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: 'Na dicotomia saussuriana, a "langue" (língua) é:',
    options: [
      "O ato individual de uso da linguagem em contexto específico",
      "O sistema coletivo e abstrato de regras compartilhadas pelos falantes",
      "A variação regional de um idioma",
      "A escrita formal e normatizada",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "O discurso indireto livre é uma técnica narrativa que:",
    options: [
      "Reproduz fielmente as falas em aspas com verbo dicendi",
      "Funde a voz do narrador com os pensamentos e falas da personagem",
      "Descreve ações sem revelar a perspectiva dos personagens",
      "Usa apenas a primeira pessoa para narrar",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "O fonema, na linguística, é definido como:",
    options: [
      "A menor unidade de som com significado próprio",
      "A menor unidade sonora capaz de distinguir palavras (sem significado próprio)",
      "A sílaba tônica de uma palavra",
      "O conjunto de sons de uma língua",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "A prosódia, como disciplina dos estudos linguísticos, ocupa-se de:",
    options: [
      "A formação de palavras por derivação e composição",
      "Os padrões de acentuação, ritmo e entonação na língua",
      "A sintaxe das orações subordinadas",
      "A semântica das metáforas",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "A denotação de uma palavra corresponde ao seu:",
    options: [
      "Sentido figurado construído pelo contexto",
      "Significado literal e primário registrado no dicionário",
      "Valor expressivo em poesia",
      "Sentido irônico em determinados contextos",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
];
