import type { QuestionSeed } from "./types";

// 16 easy (difficulty 1), 16 medium (difficulty 2), 8 hard (difficulty 3)
export const quimicaQuestions: QuestionSeed[] = [
  // ── Easy ──────────────────────────────────────────────────────────────────
  {
    body: "Qual é a fórmula molecular da água?",
    options: ["H₂O₂", "HO", "H₂O", "H₃O"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "O cloreto de sódio (NaCl) é classificado como um composto:",
    options: ["Covalente polar", "Metálico", "Iônico", "Molecular apolar"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Os elementos da Tabela Periódica são organizados em ordem crescente de:",
    options: ["Massa atômica", "Número atômico", "Número de nêutrons", "Eletronegatividade"],
    correctOptionIndex: 1,
    difficulty: 1,
    source: "ENEM 2017",
  },
  {
    body: "Qual estado da matéria possui volume definido mas não tem forma definida?",
    options: ["Sólido", "Líquido", "Gasoso", "Plasma"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Uma solução ácida possui pH:",
    options: ["Igual a 7", "Menor que 7", "Maior que 7", "Igual a 14"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Quantos elétrons de valência possui o átomo de carbono (Z = 6)?",
    options: ["2", "6", "4", "3"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "A combustão completa do metano (CH₄) produz:",
    options: ["CO₂ e H₂O", "CO e H₂", "C e H₂O", "CO₂ e H₂"],
    correctOptionIndex: 0,
    difficulty: 1,
  },
  {
    body: "A menor partícula de um elemento químico que mantém suas propriedades é o:",
    options: ["Elétron", "Átomo", "Próton", "Nêutron"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Os gases nobres se encontram no grupo:",
    options: ["1", "17", "2", "18"],
    correctOptionIndex: 3,
    difficulty: 1,
  },
  {
    body: "O hidróxido de sódio (NaOH) é classificado como:",
    options: ["Ácido forte", "Sal neutro", "Base (álcali)", "Óxido"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "O número atômico de um elemento equivale ao número de:",
    options: [
      "Nêutrons no núcleo",
      "Prótons no núcleo",
      "Elétrons na última camada",
      "Nêutrons + prótons",
    ],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Isótopos são átomos do mesmo elemento que diferem no número de:",
    options: ["Prótons", "Elétrons", "Nêutrons", "Camadas eletrônicas"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  {
    body: "Uma ligação covalente envolve:",
    options: [
      "Transferência de elétrons",
      "Compartilhamento de elétrons",
      "Atração entre íons",
      "Forças de London apenas",
    ],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "Qual é a massa molar do O₂?",
    options: ["16 g/mol", "32 g/mol", "8 g/mol", "24 g/mol"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "A destilação é uma técnica de separação baseada nas diferenças de:",
    options: ["Densidade", "Ponto de ebulição", "Solubilidade", "Massa"],
    correctOptionIndex: 1,
    difficulty: 1,
  },
  {
    body: "A oxidação corresponde à:",
    options: ["Ganho de elétrons", "Ganho de prótons", "Perda de elétrons", "Perda de prótons"],
    correctOptionIndex: 2,
    difficulty: 1,
  },
  // ── Medium ────────────────────────────────────────────────────────────────
  {
    body: "O Princípio de Le Chatelier descreve o comportamento de um sistema químico em:",
    options: [
      "Equilíbrio dinâmico perturbado",
      "Reação completa",
      "Estado inicial de reação",
      "Ausência de catalisador",
    ],
    correctOptionIndex: 0,
    difficulty: 2,
  },
  {
    body: "O pH de uma solução neutra a 25 °C é:",
    options: ["0", "7", "14", "1"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A eletrólise utiliza energia elétrica para provocar:",
    options: [
      "Reações espontâneas",
      "Reações não espontâneas (transformação química forçada)",
      "Combustão controlada",
      "Precipitação de sais",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
    source: "ENEM 2020",
  },
  {
    body: "A Lei de Hess afirma que a variação de entalpia de uma reação:",
    options: [
      "Depende do caminho percorrido",
      "É independente do caminho (só depende do estado inicial e final)",
      "É sempre positiva",
      "É zero em reações exotérmicas",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "O aumento de temperatura geralmente provoca na velocidade de uma reação química:",
    options: ["Diminuição", "Aumento", "Nenhuma mudança", "Parada completa"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "O produto de solubilidade (Ksp) está relacionado ao equilíbrio de:",
    options: [
      "Ácido-base",
      "Oxidorredução",
      "Dissolução de compostos pouco solúveis",
      "Formação de complexos",
    ],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "Os catalisadores aumentam a velocidade de reação ao:",
    options: [
      "Aumentar a temperatura",
      "Diminuir a energia de ativação",
      "Aumentar a concentração dos reagentes",
      "Modificar o ΔH",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Uma solução tampão resiste a mudanças bruscas de:",
    options: ["Temperatura", "Pressão", "pH", "Volume"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "Qual é o número de oxidação do manganês (Mn) no permanganato de potássio (KMnO₄)?",
    options: ["−1", "+2", "+7", "+4"],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "Em uma reação exotérmica, a variação de entalpia (ΔH) é:",
    options: ["Positiva (ΔH > 0)", "Negativa (ΔH < 0)", "Zero", "Indeterminada"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Um ácido fraco se ioniza:",
    options: [
      "Completamente em solução aquosa",
      "Parcialmente em solução aquosa",
      "Apenas em solventes orgânicos",
      "Não se ioniza",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A Lei de Boyle estabelece que, a temperatura constante, pressão e volume de um gás ideal são:",
    options: [
      "Diretamente proporcionais",
      "Inversamente proporcionais",
      "Independentes entre si",
      "Exponencialmente relacionados",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "A Lei de Faraday para a eletrólise relaciona a massa depositada com a:",
    options: [
      "Temperatura",
      "Pressão",
      "Carga elétrica que passa pelo sistema",
      "Concentração da solução",
    ],
    correctOptionIndex: 2,
    difficulty: 2,
  },
  {
    body: "A equação de Henderson-Hasselbalch é: pH =",
    options: ["pKa − log([A⁻]/[HA])", "pKa + log([A⁻]/[HA])", "pKb + log([HA]/[A⁻])", "−log([H⁺])"],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "Ao longo de um período da Tabela Periódica, a energia de ionização:",
    options: [
      "Diminui da esquerda para a direita",
      "Aumenta da esquerda para a direita",
      "Permanece constante",
      "Aumenta e depois diminui abruptamente",
    ],
    correctOptionIndex: 1,
    difficulty: 2,
  },
  {
    body: "O elemento com maior eletronegatividade na Tabela Periódica é o:",
    options: ["Oxigênio", "Cloro", "Nitrogênio", "Flúor"],
    correctOptionIndex: 3,
    difficulty: 2,
  },
  // ── Hard ──────────────────────────────────────────────────────────────────
  {
    body: "A hibridização do carbono no etileno (C₂H₄) é:",
    options: ["sp³", "sp²", "sp", "sd²"],
    correctOptionIndex: 1,
    difficulty: 3,
    source: "ENEM 2021",
  },
  {
    body: "O número quântico que define a forma do orbital é o:",
    options: ["Principal (n)", "Azimutal (l)", "Magnético (mₗ)", "De spin (ms)"],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "A quiralidade em moléculas orgânicas requer a presença de:",
    options: [
      "Ligação dupla C=C",
      "Um átomo de carbono quiral (espelhos não-sobreponíveis)",
      "Anel aromático",
      "Grupo funcional polar",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "A equação de Arrhenius k = Ae^(−Ea/RT) relaciona a constante de velocidade com:",
    options: [
      "A concentração dos reagentes",
      "A temperatura e a energia de ativação",
      "A pressão do sistema",
      "O número de colisões totais",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "A teoria VSEPR é usada para prever:",
    options: [
      "A reatividade de compostos orgânicos",
      "A geometria molecular",
      "A eletronegatividade dos átomos",
      "O ponto de ebulição de substâncias",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "A extração por solvente baseia-se na diferença de:",
    options: [
      "Densidades dos solventes",
      "Ponto de fusão dos compostos",
      "Solubilidade do soluto nos solventes",
      "Viscosidade dos líquidos",
    ],
    correctOptionIndex: 2,
    difficulty: 3,
  },
  {
    body: "Na substituição nucleofílica do tipo SN2, a reação procede via:",
    options: [
      "Formação de carbocátion estável",
      "Inversão de configuração (ataque pelo verso)",
      "Retenção de configuração",
      "Mecanismo radicalar",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
  {
    body: "A espectroscopia de RMN (Ressonância Magnética Nuclear) detecta:",
    options: [
      "Transições eletrônicas",
      "Transições de spin nuclear em campo magnético",
      "Vibrações de ligação química",
      "Emissão de raios X",
    ],
    correctOptionIndex: 1,
    difficulty: 3,
  },
];
